### ISSUE TITLE
included pdfs not cropped by bounding box

### ISSUE THREAD

**Issue by riedel** [Borisvl/Pdf4Eclipse#10]
If I include pdf files into other pdf files (via pdllatex  includegraphics) the cropped part appears overlayed over the other content.

If opened directly the bounding box is cropped correctly.

**Comment by Borisvl** [comment]
Can you please send me an example pdf file or upload one anywhere where this problem occurs? Maybe I can fix this problem in Sun's pdfrenderer. Otherwise, you have to wait till I have added another pdf renderer.

**Comment by riedel** [comment]
Cropped Image (renders correctly)
http://www.scribd.com/document_downloads/78130837?extension=pdf
Included into Document (does not render correctly):
http://www.scribd.com/document_downloads/78130836?extension=pdf

PS: sorry for closing an reopening the issue (I blame it on the github interface)

**Comment by Borisvl** [comment]
In version 1.1.0 I have added JPedal pdf renderer, which shows your document correct. Please upgrade to the latest version and switch to the other renderer in Pdf4Eclipse's preferences.
