### ISSUE TITLE
Diacritics are not displayed when compiling with XeLaTeX

### ISSUE THREAD

**Issue by emersonriver** [Borisvl/Pdf4Eclipse#18]
A file compiled with  XeLaTeX  and encoded in UTF-8 produces a pdf where letters with diacritics and some other characters are not displayed by Pdf4Eclipse, they are however correctly displayed by other, external viewers.

Here's an example:

\documentclass{article}
\usepackage{fontspec}
\begin{document}

a o u ä ö ü fi fa fo

\end{document}

**Comment by Borisvl** [comment]
In version 1.1.0 I added another pdf renderer which renders your documents correct.

**Comment by emersonriver** [comment]
Great, thanks!
