### ISSUE TITLE
Cannot update/install plugin

### ISSUE THREAD

**Issue by adihodos** [Borisvl/Pdf4Eclipse#19]
When trying to update/install this plugin I get the following error :
An error occurred while collecting items to be installed
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: osgi.bundle,de.vonloesch.pdf4eclipse.help,1.1.0.
http://borisvl.github.com/Pdf4Eclipse/plugins/de.vonloesch.pdf4eclipse.help_1.1.0

I'm using Linux Mint 12, X64, Eclipse X64 (tried both 3.7.2 and 4.1.1).

**Comment by Borisvl** [comment]
Hi, I fixed a typo in TeXlipse update site. Installation/Update should work now.

**Comment by adihodos** [comment]
Thank you, it works now. This issue can be closed.
