### ISSUE TITLE
Pdf4Eclipse plugin fails on Eclipse 4.2 (Juno) install

### ISSUE THREAD

**Issue by jmenriquem** [Borisvl/Pdf4Eclipse#22]
When installing pdf4eclipse plugin on eclipse 4.2 (Juno), I get the following message:

An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.update.ui,3.2.300.v20100512

Perhaps it is not an issue with pdf4eclipse, but the fact is that pdf4eclipse plugin cannot be installed.

**Comment by Borisvl** [comment]
I am not sure whether this has something to do with pdf4eclipse. Can you please provide more informations, like the relevant lines in the log file?

**Comment by Borisvl** [comment]
I have tried it by myself and had no problems with installing it. Pdf4Eclipse runs flawless on eclipse Juno. I am closing this issue, please reopen it, if you still have installation problems that are related to pdf4eclipse.

**Comment by jmenriquem** [comment]
I have made some testings and finally I could install pdf4eclipse on Ubuntu 12.04 32 bits and eclipse Juno 4.2 successfully. However, It still fails on Ubuntu 12.04 64 bits and eclipse Juno 4.2. I am continuously getting the following error message:

An error occurred while installing the items
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]de.vonloesch.pdf4Eclipse 1.1.0.201204091136, action=).
Failed to prepare partial IU: [R]de.vonloesch.pdf4Eclipse 1.1.0.201204091136.

**Comment by jmenriquem** [comment]
--- SOLVED ----

The issues installing/upgrading were solved unchecking the box “Contact all update sites during install to find required software”.
