### ISSUE TITLE
Change shortcut for forward search

### ISSUE THREAD

**Issue by monamonamona** [Borisvl/Pdf4Eclipse#4]
I liked pdf4eclipse but I removed it because I was unable to write latex.

Using the slovenian keyboard the shortcut for the [ bracket is AltGr+F. However, when Pdf4Eclipse is installed this shortcut launches the forward search, thus making it impossible to insert the [ bracket, which is widely used in Latex. 

Thus I suggest that the shorcut is configurable or that it is possible to remove it.

**Comment by Borisvl** [comment]
This bug is already fixed in the repository :). I will release a new
version soon.

**Comment by Borisvl** [comment]
Fixed in version 1.0.2
