### ISSUE TITLE
Tested in Ubuntu 11.04?

### ISSUE THREAD

**Issue by ghost** [Borisvl/Pdf4Eclipse#7]
Hi,

I am really excited about this idea.  I've been looking for something just like this for a while.  I'm just wondering if this has been tested in Ubuntu 11.04?  It installs fine and the forward and backward searching work great.  However, I can't scroll between pages of the pdf.  I've tried the scroll wheel on the mouse, arrow keys, pg up/down, etc.  Entering the page numbers at the bottom of the screen also doesn't help.   Any idea how to fix this?

Thanks!

**Comment by Borisvl** [comment]
No, I did not test it in Ubuntu, but in another Linux distribution and did not have any problems with navigation. You should be able to go to the next page with page down if you are at the end of a page. Did this problem occurs with any pdf file? 

This bug seems to be similar to #5.

**Comment by ghost** [comment]
You are right.  I guess I hadn't tried page down yet.  Page down/up work great.  The scroll wheel and arrow keys don't work, however.  Also, I can't go to a page by entering the page numbers.

Thanks for the cool product.  I'm looking forward to future upgrades, especially continuous scrolling.
